# Generated by Django 5.0.9 on 2025-05-30 22:13

import django.db.models.deletion
import django_extensions.db.fields
import logme.projects.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'])),
                ('color_hex', logme.projects.models.fields.HexColorField(default='COCOCO', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('framework', models.CharField(choices=[('LARAVEL', 'Laravel')], default=('LARAVEL', 'Laravel'))),
                ('file_path', models.CharField(max_length=255)),
                ('pattern', models.CharField(blank=True, help_text='\n            Regex pattern needed to parse the first line of a log into the date,\n            level, summary, and initial trace. The framework default will be\n            used if no custom pattern is provided\n        ', max_length=255)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.connection')),
                ('levels', models.ManyToManyField(related_name='projects', to='projects.loglevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('trace', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='projects.loglevel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='projects.project')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
