# Generated by Django 5.0.9 on 2025-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='project',
            name='levels',
        ),
        migrations.DeleteModel(
            name='LogLevel',
        ),
    ]
