# Generated by Django 5.0.9 on 2025-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identity_file', models.FilePathField(blank=True, match='.*\\.pem$', max_length=255, null=True, path='/', recursive=True)),
                ('password', models.CharField(blank=True, help_text='Password for authentication. Required if no identity file is provided.', max_length=255, null=True)),
                ('host', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
