# Generated by Django 5.0.9 on 2025-05-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identity_file', models.FilePathField(match='.*\\.pem$', max_length=255, path='/', recursive=True)),
                ('password', models.CharField(help_text='\n            Password for authentication.\n            Required if no identity file is provided.\n        ', max_length=255)),
                ('host', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
