# Generated by Django 5.0.9 on 2025-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='connection',
            name='identity_file',
            field=models.FilePathField(blank=True, match='.*\\.pem$', max_length=255, path='/', recursive=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(blank=True, help_text='\n            Password for authentication.\n            Required if no identity file is provided.\n        ', max_length=255),
        ),
    ]
