# Generated by Django 5.0.9 on 2025-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='identity_file',
            field=models.FilePathField(match='.*\\.pem$', max_length=255, null=True, path='/', recursive=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(help_text='\n            Password for authentication.\n            Required if no identity file is provided.\n        ', max_length=255, null=True),
        ),
    ]
