# Generated by Django 5.0.9 on 2025-06-02 22:54

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_connection_identity_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
