# Generated by Django 5.0.9 on 2025-06-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_connection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
