# Generated by Django 5.0.9 on 2024-11-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_loglevel_project_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sync_command',
            field=models.TextField(blank=True, null=True),
        ),
    ]
