# Generated by Django 5.0.9 on 2024-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_remove_logentry_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='label',
        ),
        migrations.AddField(
            model_name='logentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
