# Generated by Django 5.0.9 on 2024-11-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_remove_logentry_label_logentry_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={},
        ),
        migrations.AddConstraint(
            model_name='logentry',
            constraint=models.UniqueConstraint(fields=('summary', 'timestamp'), name='unique_summary_timestamp'),
        ),
    ]
