# Generated by Django 5.0.9 on 2024-12-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_alter_logentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-timestamp']},
        ),
    ]
