# Generated by Django 5.0.9 on 2024-12-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_alter_logentry_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='log_type',
            new_name='framework',
        ),
    ]
