# Generated by Django 5.0.9 on 2024-12-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_rename_log_type_project_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='pattern',
            field=models.CharField(help_text='\n            Regex pattern needed to parse the first line of a log into the date,\n            level, summary, and initial trace. The framework default will be\n            used if no custom pattern is provided\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='sync_command',
            field=models.TextField(blank=True, help_text='\n            Command to copy log file from its home location to this project.\n            Use `{here}` for the destination. The `cp` command is a good\n            choice for local projects and `scp` for remote projects.,\n        '),
        ),
    ]
