# Generated by Django 5.0.9 on 2025-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_logentry_is_read_alter_project_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pattern',
            field=models.CharField(help_text='\n            Regex pattern needed to parse the first line of a log into the date,\n            level, summary, and initial trace. The framework default will be\n            used if no custom pattern is provided\n        ', max_length=255, null=True),
        ),
    ]
