# Generated by Django 5.0.9 on 2025-01-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_alter_project_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pattern',
            field=models.CharField(blank=True, default='', help_text='\n            Regex pattern needed to parse the first line of a log into the date,\n            level, summary, and initial trace. The framework default will be\n            used if no custom pattern is provided\n        ', max_length=255),
            preserve_default=False,
        ),
    ]
